#!/bin/bash


#This tool for beginners change macaddrr
#This same as  macchager
#
#
function Help(){
echo "Usage: macwlan wlan0-9"
echo "Write name in wlan0 or eth0"
echo
echo "macwlan wlan0"
}

var=$1
function mac () {
sudo ifconfig $var down
sudo macchanger -r $var
sudo macchanger -r $var
sudo macchanger -r $var
sudo ifconfig $var up
echo
show=$(macchanger -s $var )
echo ${show:42:-10} #  ShowPermanent Mac
echo ${show::-52} # Show Current Mac
}

if [[ -z "$var" ]];then
 Help   
 
 elif [[ -n "$var" ]];then
  	 mac
fi



