#!/bin/bash

function help_function() {
    echo "Usage: macwlan <interface>"
    echo "Write the name of the network interface (e.g., wlan0, eth0)"
    echo
    echo "Example: macwlan wlan0"
}

function change_mac() {
    local var=$1

    if [[ -z "$var" ]]; then
        help_function
        exit 1
    fi

    sudo ifconfig "$var" down

    # Change MAC address
    sudo macchanger -r "$var"

    sudo ifconfig "$var" up
    echo

    # Get the MAC addresses
    local show
    show=$(macchanger -s "$var")

    # Show Permanent MAC
    echo "Permanent MAC: ${show:42:-10}"
    # Show Current MAC
    echo "Current MAC: ${show:13:17}"
}

# Main script logic
if [[ -z "$1" ]]; then
    help_function
else
    change_mac "$1"
fi
